### ISSUE TITLE
YAML对android库依赖?

### ISSUE THREAD

**Issue by nobodxbodon** [HL4A/HL4A#3]
https://github.com/HL4A/HL4A/blob/master/%E6%95%B0%E6%8D%AE/YAML/src/main/java/%E9%97%B4/%E6%95%B0%E6%8D%AE/YAML.java#L37

这里用了android库的Log方法, 但build.gradle中没有. 不知为何不会出错? 是因为调用这个`解析`方法的在运行时都没用到?

**Comment by MikaGuraN** [comment]
写错了，我去删掉

**Comment by MikaGuraN** [comment]
当时我是测试...结果忘了删233
